Update
JoelRoxell/r-swipeable pull request #10
Opened 2016-10-27 07:44 UTC by widenanders

Update to make more dynamic

2016-10-28 10:00 UTC, JoelRoxell requested changes

2016-10-28 10:00 UTC, JoelRoxell commented on src/swipeable.js
> +
Remove new line.

2016-10-28 10:00 UTC, JoelRoxell commented on lib/style.js
> +exports.default = styles;
Missing line break.

2016-10-28 10:00 UTC, JoelRoxell commented on src/swipeable.js
> +    const totalWidth = childNodes[0].offsetWidth * childNodes.length;;
Missing line break and remove duplication of `;`

2016-10-28 10:00 UTC, JoelRoxell commented on src/swipeable.js
> +    return -Math.abs(totalWidth);
`return (- totalWidth);`

2016-10-28 10:00 UTC, JoelRoxell commented on src/swipeable.js
> +  applyDisplayRuleToChildNodes() {
Missing documentation.

2016-10-28 10:00 UTC, JoelRoxell commented on src/swipeable.js
> +      this.content.childNodes[i].style.display = 'inline-block';
Please secure with use `hasOwnProperty`.

2016-11-02 13:24 UTC, widenanders commented on src/swipeable.js
> +      this.content.childNodes[i].style.display = 'inline-block';
I don't really understand why this is necessary, what property am I supposed to check for?

2016-11-02 14:14 UTC, JoelRoxell approved these changes

2016-11-06 21:19 UTC, merged